[package]
name = "protobuf-example"
version = "1.0.0"
authors = ["curoky <cccuroky@gmail.com>"]
publish = false
edition = "2021"

[dependencies]
protobuf = "3.1.0"
protobuf-json-mapping = "3.1.0"
proto_echo_idl = { path = "../idl" }
