# cc_test(
#     name = "observer",
#     testonly = False,
#     srcs = [
#         "observer.cc",
#         "echo_handler.h",
#     ] + ["//tutorial/fbthrift/echo/idl:echo_fbthrift"],
#     copts = TEST_CPP_COPTS,
#     linkopts = TEST_LINKOPTS,
#     deps = [
#         "//source/fbthrift",
#         "@com_github_catchorg_catch2//:catch2_main",
#     ],
# )
